### PR TITLE
Update geometry optimization

### LINKED ISSUE #82: add test for geom opt convergence
there needs to be some testing for when the geometry optimisation does not converge in a specified number of steps and raises some error

### PR DESCRIPTION
**Pull request by ElliottKasoar**
Resolves #82 and #83

- Replaces `dyn_kwargs `with `steps` option
  - Originally planned just for the CLI, but I can't see anything that allows any other options to be passed to `dyn.run` other than `steps` and `fmax`, so it seemed sensible to just replace it (we can always add the option again if it proves useful later)
- Adds convergence warning if fmax is not met
- Adds tests for restarting optimization via Python and CLI

To do(?)

- [ ] Store maximum force
  - This doesn't seem to be immediately accessible, as [only the boolean seems to be returned](https://gitlab.com/ase/ase/-/blob/master/ase/utils/abc.py#L32) (note: implemented slightly differently in the last tagged version, but still not stored)
  - We don't need it for the convergence test, so we'd have to calculate additionally anyway
- [ ] traj_kwargs
  - Probably not needed for now? Adding steps was the main motivation for #83

### CODE REVIEW

**Comment by alinelena** [comment]
> Resolves #82 and #83
> 
> * Replaces `dyn_kwargs `with `steps` option
>   
>   * Originally planned just for the CLI, but I can't see anything that allows any other options to be passed to `dyn.run` other than `steps` and `fmax`, so it seemed sensible to just replace it (we can always add the option again if it proves useful later)
> * Adds convergence warning if fmax is not met
> * Adds tests for restarting optimization via Python and CLI
> 
> To do(?)
> 
> * [ ]  Store maximum force
>   
>   * This doesn't seem to be immediately accessible, as [only the boolean seems to be returned](https://gitlab.com/ase/ase/-/blob/master/ase/utils/abc.py#L32) (note: implemented slightly differently in the last tagged version, but still not stored)
>   * We don't need it for the convergence test, so we'd have to calculate additionally anyway
> * [ ]  traj_kwargs
>   
>   * Probably not needed for now? Adding steps was the main motivation for [Add options for dyn_kwargs, filter_kwargs and opt_kwargs via CLI #83](https://github.com/stfc/janus-core/issues/83)

**Comment by alinelena** [comment]
this was closed by my siliness

**Comment by alinelena** [comment]
reopen

**Comment by ElliottKasoar** [comment]
Ah I don't think it will let us since I squashed the typo commits, I'll open a new one

**Comment by alinelena** [comment]
ok, sorry for mistake

**Pull request closed without merging**
