### PR TITLE
Ensure config options are valid

### LINKED ISSUE #103: Investigate error for non-existent config args
> There will still be a `-` vs `_` difference, but probably close enough otherwise.
> 
> It would be much less of an issue if it didn't allow unspecified options too, so I need to figure out if that's fixable too

_Originally posted by @ElliottKasoar in https://github.com/stfc/janus-core/pull/100#discussion_r1553919917_

### PR DESCRIPTION
**Pull request by ElliottKasoar**
Resolves #103

Compares the options defined in configuration file to CLI function options to ensure only valid options are defined.

Also restructures code, as the CLI module was getting a bit unwieldy. This is entirely done within the first commit, so happy to separate out into two PRs if preferable.

### CODE REVIEW

**Comment by ElliottKasoar** [comment]
> My primary comment is that I think the restructure (which looks good) should be separated from any changes/additions.

Yeah, it became much bigger than I'd originally planned. I've separated the commit for #120, so this can be rebased once we're happy with that.

**Comment by alinelena** [comment]
> My primary comment is that I think the restructure (which looks good) should be separated from any changes/additions.

can we let it go this time? in interest of time, @ElliottKasoar will note this

**Comment by oerc0122** [comment]
> > My primary comment is that I think the restructure (which looks good) should be separated from any changes/additions.
> 
> can we let it go this time? in interest of time, @ElliottKasoar will note this

It's been done

**Comment by alinelena** [comment]
> > > My primary comment is that I think the restructure (which looks good) should be separated from any changes/additions.
> > 
> > 
> > can we let it go this time? in interest of time, @ElliottKasoar will note this
> 
> It's been done

perfect... then will get the merge way

**Review by alinelena — APPROVED** [review]

**Review by oerc0122 — APPROVED** [review]

**Pull request merged**
